# Generated by Django 4.0.2 on 2022-02-15 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transacoes', '0002_rename_value_money_transaction_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='amount',
        ),
    ]
