# Generated by Django 4.0.2 on 2022-02-15 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transacoes', '0003_remove_transaction_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Preço:'),
        ),
    ]
